# Autogenerated code.
import click


class CLI(click.MultiCommand):
    """
    Helper of {{name}}
    """
    commands = {'sub': None}

    def __init__(self):
        super(__class__, self).__init__(name={{name}}, help=__class__.__doc__)

    def list_commands(self, ctx):
        return sorted(self.commands.keys())

    def get_command(self, ctx, name):
        from . import service
        if name in self.commands and self.commands[name] is None:
            self.commands[name] = getattr(service, name)
        return self.commands.get(name)


{{name}} = CLI()
